// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkroyRAO7-fswHkcONQO3FXqeYsbVEDHY',
    appId: '1:604823459593:web:030acfda280df7032925d8',
    messagingSenderId: '604823459593',
    projectId: 'flutter-application-todo',
    authDomain: 'flutter-application-todo.firebaseapp.com',
    storageBucket: 'flutter-application-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo94mBN7chrBi99ftilKeAye1myhg3wik',
    appId: '1:604823459593:android:36d09a6bf074c7d22925d8',
    messagingSenderId: '604823459593',
    projectId: 'flutter-application-todo',
    storageBucket: 'flutter-application-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE9Nk6VG2CBvwNP-lKdisSNFatX4kw0_o',
    appId: '1:604823459593:ios:7e4ff03c7a43d7a52925d8',
    messagingSenderId: '604823459593',
    projectId: 'flutter-application-todo',
    storageBucket: 'flutter-application-todo.appspot.com',
    iosClientId: '604823459593-ehcmm328023q7g76ckpspti4sc9ur76m.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE9Nk6VG2CBvwNP-lKdisSNFatX4kw0_o',
    appId: '1:604823459593:ios:7e4ff03c7a43d7a52925d8',
    messagingSenderId: '604823459593',
    projectId: 'flutter-application-todo',
    storageBucket: 'flutter-application-todo.appspot.com',
    iosClientId: '604823459593-ehcmm328023q7g76ckpspti4sc9ur76m.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
